# File generated by CompCert 3.10
# Command line: test_stage/test.b -db -S -o test_stage/test.s
	.text
	.align	16
	.globl $96
$96:
	.cfi_startproc
	subq	$8, %rsp
	.cfi_adjust_cfa_offset	8
	leaq	16(%rsp), %rax
	movq	%rax, 0(%rsp)
	leaq	0(%rdi,%rsi,1), %rax
	addq	$8, %rsp
	ret
	.cfi_endproc
	.type	$96, @function
	.size	$96, . - $96
